
ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS client text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS year text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS verticals text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS challenge_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS challenge_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS approach_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS approach_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS outcome_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS outcome_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS metrics jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS gallery jsonb NOT NULL DEFAULT '[]'::jsonb;
