
ALTER TABLE public.profile_settings
  ADD COLUMN IF NOT EXISTS experience_eyebrow_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_eyebrow_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_title_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_title_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_lane_work_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_lane_work_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_lane_study_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_lane_study_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_tag_work_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_tag_work_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_tag_study_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS experience_tag_study_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS projects_eyebrow_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS projects_eyebrow_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS projects_title_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS projects_title_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS skills_eyebrow_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS skills_eyebrow_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS skills_title_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS skills_title_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_cta_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_cta_en text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_cta_alt_es text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_cta_alt_en text NOT NULL DEFAULT '';

UPDATE public.profile_settings SET
  experience_eyebrow_es = COALESCE(NULLIF(experience_eyebrow_es,''), 'Trayectoria'),
  experience_eyebrow_en = COALESCE(NULLIF(experience_eyebrow_en,''), 'Journey'),
  experience_title_es = COALESCE(NULLIF(experience_title_es,''), 'De LATAM a los Estados Unidos.'),
  experience_title_en = COALESCE(NULLIF(experience_title_en,''), 'From LATAM to the United States.'),
  experience_lane_work_es = COALESCE(NULLIF(experience_lane_work_es,''), 'Experiencia'),
  experience_lane_work_en = COALESCE(NULLIF(experience_lane_work_en,''), 'Experience'),
  experience_lane_study_es = COALESCE(NULLIF(experience_lane_study_es,''), 'Educación'),
  experience_lane_study_en = COALESCE(NULLIF(experience_lane_study_en,''), 'Education'),
  experience_tag_work_es = COALESCE(NULLIF(experience_tag_work_es,''), 'Trabajo'),
  experience_tag_work_en = COALESCE(NULLIF(experience_tag_work_en,''), 'Work'),
  experience_tag_study_es = COALESCE(NULLIF(experience_tag_study_es,''), 'Estudio'),
  experience_tag_study_en = COALESCE(NULLIF(experience_tag_study_en,''), 'Study'),
  projects_eyebrow_es = COALESCE(NULLIF(projects_eyebrow_es,''), 'Campañas seleccionadas'),
  projects_eyebrow_en = COALESCE(NULLIF(projects_eyebrow_en,''), 'Selected campaigns'),
  projects_title_es = COALESCE(NULLIF(projects_title_es,''), 'Verticales donde he ejecutado.'),
  projects_title_en = COALESCE(NULLIF(projects_title_en,''), 'Verticals I''ve executed in.'),
  skills_eyebrow_es = COALESCE(NULLIF(skills_eyebrow_es,''), 'Capacidades'),
  skills_eyebrow_en = COALESCE(NULLIF(skills_eyebrow_en,''), 'Capabilities'),
  skills_title_es = COALESCE(NULLIF(skills_title_es,''), 'Estrategia, datos y liderazgo.'),
  skills_title_en = COALESCE(NULLIF(skills_title_en,''), 'Strategy, data and leadership.'),
  hero_cta_es = COALESCE(NULLIF(hero_cta_es,''), 'Descargar CV'),
  hero_cta_en = COALESCE(NULLIF(hero_cta_en,''), 'Download CV'),
  hero_cta_alt_es = COALESCE(NULLIF(hero_cta_alt_es,''), 'Contactar'),
  hero_cta_alt_en = COALESCE(NULLIF(hero_cta_alt_en,''), 'Get in touch')
WHERE singleton = true;
